#-----------------------------------------------------------------------------
#
#  Configuration for continuous integration service at travis-ci.org
#
#-----------------------------------------------------------------------------

language: cpp

sudo: false

git:
  depth: 2

# don't re-build for tags so that [publish binary] is not re-run
# https://github.com/travis-ci/travis-ci/issues/1532
branches:
  except:
    - /^v[0-9]/

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     - pkg-config
     - make
     - libstdc++-4.8-dev

cache:
  directories:
  - $HOME/.ccache

matrix:
  include:
     # Linux
     - os: linux
       compiler: clang
       env: NODE_VERSION="4"
     - os: linux
       compiler: clang
       env: NODE_VERSION="6"
     - os: linux
       compiler: clang
       env: NODE_VERSION="8"
     # OS X
     - os: osx
       osx_image: xcode8
       compiler: clang
       env: NODE_VERSION="4"
     - os: osx
       osx_image: xcode8
       compiler: clang
       env: NODE_VERSION="6"
     - os: osx
       osx_image: xcode8
       compiler: clang
       env: NODE_VERSION="8"

env:
  global:
   - JOBS: 8
   - CLANG_VERSION: "4.0.1"
   - secure: Ac0sNxaMmm/4NLJwjB5W74wNNrXH2cFz4qADJSJwGr+p78NVrp+3B70Nlffg6sf6sq57KeoQi5EbUNSa4fjLS2FqJJDr5U8cOA4nt5tPGm8cucdAyr4VCREEddtV4jfIcNN0/I/DKIK4d744SmpqomVYqTUFOVK8LOT4vAX3tTo=
   - secure: bsD0VyN6F6+ratG/C2AB1GrbmaPGyvaAgjZXd7tsQPYl+TR3BT643T9GikgN5IJdbjVBOJDfSqk76g/UlfLl9bRnoybP8tJsZJhCyMYKyRNGJZBIOyEVe6j5FrcT5ejBO0EIGaw2fXwSkG92pg7CFQOAPkVNgcl/H0XNdMa3Q/8=

before_install:
 # workaround travis rvm bug
 # https://github.com/travis-ci/travis-ci/issues/6307
 # http://superuser.com/questions/1044130/why-am-i-having-how-can-i-fix-this-error-shell-session-update-command-not-f
- |
  if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
    rvm get head || true
  fi
- scripts/validate_tag.sh
- if [[ $(uname -s) == 'Darwin' ]]; then brew uninstall --force node; fi;
- source ./scripts/install_node.sh ${NODE_VERSION}

install:
- source ./bootstrap.sh
- if [[ $(uname -s) == 'Linux' ]]; then
     ./mason/mason install clang++ ${CLANG_VERSION};
     export PATH=$(./mason/mason prefix clang++ ${CLANG_VERSION})/bin:${PATH};
     export CXX="ccache clang++ -Qunused-arguments";
     export CC="ccache clang -Qunused-arguments";
     $CXX --version
     export PYTHONPATH=$(pwd)/mason_packages/.link/lib/python2.7/site-packages;
   else
     export PYTHONPATH=$(pwd)/mason_packages/.link/lib/python/site-packages;
   fi;
- git clone --depth=1 --branch=$(node -e "console.log(require('./package.json').libosmium_version)") https://github.com/osmcode/libosmium.git ../libosmium
- git clone --depth=1 --branch=$(node -e "console.log(require('./package.json').protozero_version)") https://github.com/mapbox/protozero.git ../protozero

before_script:
- if [[ ${COVERAGE} == true ]]; then
    PYTHONUSERBASE=$(pwd)/mason_packages/.link pip install --user cpp-coveralls;
    make coverage;
  else
    make;
  fi;
- nm lib/binding/osmium.node | grep "GLIBCXX_3.4.2[0-9]" || true
- npm test
- ./scripts/coverage.sh

script:
- ./scripts/publish.sh
