#-----------------------------------------------------------------------------
#
#  Configuration for continuous integration service at appveyor.com
#
#-----------------------------------------------------------------------------

# branches to build
branches:
  # whitelist
  only:
    - master

# Operating system (build VM template)
os: Visual Studio 2014 CTP4

# scripts that are called at very beginning, before repo cloning
init:

# clone directory
clone_folder: c:\projects\node-osmium

platform: x64

install:
  - CALL "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  - SET LODEPSDIR=c:\projects\node-osmium\libosmium-deps
  - SET PROJ_LIB=%LODEPSDIR%\proj\share
  - set GDAL_DATA=%LODEPSDIR%\gdal\data
  #geos.dll
  - SET PATH=%LODEPSDIR%\geos\lib;%PATH%
  #gdal.dll
  - SET PATH=%LODEPSDIR%\gdal\lib;%PATH%
  #libexpat.dll
  - SET PATH=%LODEPSDIR%\expat\lib;%PATH%
  #libtiff.dll
  - SET PATH=%LODEPSDIR%\libtiff\lib;%PATH%
  #zlibwapi.dll
  - SET PATH=%LODEPSDIR%\zlib\lib;%PATH%
  - SET PATH=%CD%;%PATH%;
  - ps: Start-FileDownload https://mapnik.s3.amazonaws.com/dist/dev/libosmium-deps-win-14.0-x64.7z -FileName lodeps.7z
  - ps: Start-FileDownload "https://mapbox.s3.amazonaws.com/node-cpp11/v0.10.33/x64/node.exe"
  - 7z x lodeps.7z > nul
  - echo %LODEPSDIR%
  - dir %LODEPSDIR%
  - git clone https://github.com/osmcode/libosmium.git ../libosmium

build_script:
  - cd c:\projects\node-osmium
  - node -v
  - node -e "console.log(process.arch,process.execPath)"
  - npm install --build-from-source --msvs_version=2013 --dist-url=https://s3.amazonaws.com/mapbox/node-cpp11 --toolset=v140
  - npm test

test: off

deploy: off

